---
- name: "add new group {{ item.group }}"
  group:
    name: "{{ item.group | default(item.name) }}"
    state: "{{ item.state | default('present') }}"
  when: item.name != 'root'

- name: "manage user {{ item.name }}"
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment | default(item.name) }}"
    group: "{{ item.group | default(item.name) }}"
    groups: "{{ item.groups | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    shell: '{{ item.shell | default("/bin/bash")}}'
    home: "{{ item.home_path | default(omit) }}"
    createhome: "{{ item.createhome | default(true) }}"
    state: "{{ item.state | default('present') }}"
  when: item.name != 'root'

- name: "deploy public keys for {{ item.name }}"
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.sshpubkey }}"
    exclusive: "{{ item.exclusive | default('true') }}"
    state: "{{ item.state | default('present') }}"
  when: item.name != 'root' and item.sshpubkey is defined
  register: pubkey

- name: "set permissions on keyfile"
  file:
    path: "{{ pubkey.keyfile }}"
    mode: "{{ item.keyfile_mode }}"
  when: item.name != 'root' and item.keyfile_mode is defined
...
